"""uniformscore table

Revision ID: 444fe84b4fdc
Revises: cf78afa70178
Create Date: 2019-09-25 21:17:22.616909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444fe84b4fdc'
down_revision = 'cf78afa70178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_check_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('score1', sa.Integer(), nullable=True),
    sa.Column('score2', sa.Integer(), nullable=True),
    sa.Column('score3', sa.Integer(), nullable=True),
    sa.Column('score4', sa.Integer(), nullable=True),
    sa.Column('score5', sa.Integer(), nullable=True),
    sa.Column('score6', sa.Integer(), nullable=True),
    sa.Column('score7', sa.Integer(), nullable=True),
    sa.Column('score8', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_check_scores')
    # ### end Alembic commands ###
